{% set name = "chembl_structure_pipeline" %}
{% set version = "1.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/chembl/ChEMBL_Structure_Pipeline/archive/{{ version }}.tar.gz
  sha256: a553b95ce198afdf99737e14ab11db639d09ff06b74fd192bb3d3a680ad88def

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - rdkit >=2022.09.01
  run:
    - python >=3.7
    - rdkit >=2022.09.01

test:
  imports:
    - chembl_structure_pipeline

about:
  home: https://github.com/chembl/ChEMBL_Structure_Pipeline
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: ChEMBL database structure pipelines

extra:
  recipe-maintainers:
    - hadim
