{% set name = "chembl_structure_pipeline" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/chembl/ChEMBL_Structure_Pipeline/archive/{{ version }}.tar.gz
  sha256: fb332267e09b63d5c4939c1cd06818f71da8539e8d308e803b616533a02184bb

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - rdkit >=2019.09.2
  run:
    - python
    - rdkit >=2019.09.2

test:
  imports:
    - chembl_structure_pipeline

about:
  home: https://github.com/chembl/ChEMBL_Structure_Pipeline
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: ChEMBL database structure pipelines

extra:
  recipe-maintainers:
    - hadim
