{% set name = "chembl_structure_pipeline" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/chembl/ChEMBL_Structure_Pipeline/archive/{{ version }}.tar.gz
  sha256: 58651c7ca12f6318ca1a167cb1284124ac227d08314d02f2aceafac904557309

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - rdkit >=2022.09.01
  run:
    - python >={{ python_min }}
    - rdkit >=2022.09.01

test:
  requires:
    - python {{ python_min }}
  imports:
    - chembl_structure_pipeline

about:
  home: https://github.com/chembl/ChEMBL_Structure_Pipeline
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: ChEMBL database structure pipelines

extra:
  recipe-maintainers:
    - hadim
