context:
  name: chembl_structure_pipeline
  version: "1.2.3"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/chembl/ChEMBL_Structure_Pipeline/archive/${{ version }}.tar.gz
  sha256: 1f0b739302f95ccbceba64bc88d72d7dde3762876818188939d4d29ea65c2797

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - rdkit >=2022.09.01

tests:
  - python:
      imports:
        - chembl_structure_pipeline
      python_version: ${{ python_min }}.*

about:
  license: MIT
  license_file: LICENSE
  summary: ChEMBL database structure pipelines
  homepage: https://github.com/chembl/ChEMBL_Structure_Pipeline

extra:
  recipe-maintainers:
    - hadim
